### ISSUE TITLE
Improve situation when new spacy version gets published

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/spacy-models-feedstock#5]
It seems recently a new spacy version got published (3.5), without there yet being spacy models for this version.

What happens in a feedstock where I have a test-dependency on space-models-en_core_web_sm is that now it pulls in a really old build:
```
    spacy:                      3.5.0-py38h507a481_0        conda-forge
    spacy-legacy:               3.0.12-pyhd8ed1ab_0         conda-forge
    spacy-loggers:              1.0.4-pyhd8ed1ab_0          conda-forge
    spacy-model-en_core_web_sm: 2.3.1-pyh9f0ad1d_0          conda-forge
```
that then fails `pip check`:
```
+ pip check
en-core-web-sm 2.3.1 has requirement spacy<2.4.0,>=2.3.0, but you have spacy 3.5.0.
```

It seems this is a question of the metadata of the old spacy-model-* builds having bad metadata (not depending hard enough on a given spacy version), so the resolver believes it found a non-conflicting solution, while keeping the newest spacy...

It seem to me that we should patch the old metadata; additionally/ideally, the faster `spacy-models-*` follows a new spacy version, the better.

**Comment by bollwyvl** [comment]
Yep patching the old metadata would work. I'll work on getting the new one out, in the meantime, but there's only so much we can do...

**Comment by h-vetinari** [comment]
> I'll work on getting the new one out, in the meantime, but there's only so much we can do...

Yeah, this is not to stress you here in getting a new model version out, but to ensure that during that time-period, we don't produce broken environments.

**Comment by h-vetinari** [comment]
It might be easiest to just patch in a global `spacy<3` cap to all spacy-model-* 2.x packages.

**Comment by bollwyvl** [comment]
Ok, #6 is merged.

Also ran into:
- https://github.com/conda-forge/transformers-feedstock/issues/106#issuecomment-1413844866
- expanded https://github.com/conda-forge/spacy-models-feedstock/issues/2

@h-vetinari Are you going to make the repodata patches PR? I haven't done that before.

**Comment by h-vetinari** [comment]
> @h-vetinari Are you going to make the repodata patches PR? I haven't done that before.

Opened https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/396 for you. Now you know how to do it! :)
